name: Bilibili Dynamic Monitor

on:
  schedule:
    - cron: "*/10 * * * *"  # 每10分钟运行一次
  workflow_dispatch:        # 手动触发按钮

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run monitor script
        run: python bilibili_monitor.py
